"""Generate an SVG stats dashboard for README.md.

Run: python scripts/update-readme-stats.py
Outputs: .github/assets/stats.svg + updates README.md embed
"""

import json
import re
from pathlib import Path
from collections import Counter

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
SVG_PATH = ROOT / ".github" / "assets" / "stats.svg"


def compute_stats():
    edges = json.loads((ROOT / "data/edges.json").read_text())
    orgs = [json.loads(f.read_text()) for f in (ROOT / "data/orgs").glob("*.json")]

    return {
        "orgs": len(orgs),
        "edges": len(edges),
        "evidence": sum(1 for e in edges if e.get("evidence")),
        "active": sum(1 for o in orgs if o.get("status") == "active"),
        "inactive": sum(1 for o in orgs if o.get("status") == "inactive"),
        "rivalry": sum(1 for e in edges if e["type"] == "rivalry"),
        "alliance": sum(1 for e in edges if e["type"] == "alliance"),
        "member_of": sum(1 for e in edges if e["type"] == "member_of"),
        "spin_off": sum(1 for e in edges if e["type"] == "spin_off"),
    }


def generate_svg(stats: dict) -> str:
    evidence_pct = stats["evidence"] * 100 // stats["edges"]
    bar_w = 160
    evidence_bar = bar_w * evidence_pct // 100
    rivalry_bar = bar_w * stats["rivalry"] // stats["edges"]
    alliance_bar = bar_w * stats["alliance"] // stats["edges"]

    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="820" height="180" fill="none">
  <style>
    .bg {{ fill: #0d1117; rx: 8; }}
    .card {{ fill: #161b22; rx: 6; }}
    .title {{ fill: #e6edf3; font: 600 13px -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; }}
    .value {{ fill: #e6edf3; font: 700 22px -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; }}
    .label {{ fill: #7d8590; font: 400 11px -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; }}
    .bar-bg {{ fill: #21262d; rx: 3; }}
    .bar-evidence {{ fill: #3fb950; rx: 3; }}
    .bar-rivalry {{ fill: #f85149; rx: 3; }}
    .bar-alliance {{ fill: #58a6ff; rx: 3; }}
  </style>

  <!-- Background -->
  <rect class="bg" width="820" height="180"/>

  <!-- Row 1: Big numbers -->
  <rect class="card" x="16" y="16" width="150" height="70"/>
  <text class="value" x="91" y="50" text-anchor="middle">{stats['orgs']:,}</text>
  <text class="label" x="91" y="68" text-anchor="middle">Organizations</text>

  <rect class="card" x="182" y="16" width="150" height="70"/>
  <text class="value" x="257" y="50" text-anchor="middle">{stats['edges']:,}</text>
  <text class="label" x="257" y="68" text-anchor="middle">Relationships</text>

  <rect class="card" x="348" y="16" width="150" height="70"/>
  <text class="value" x="423" y="50" text-anchor="middle">{stats['active']:,}</text>
  <text class="label" x="423" y="68" text-anchor="middle">Active</text>

  <rect class="card" x="514" y="16" width="150" height="70"/>
  <text class="value" x="589" y="50" text-anchor="middle">{stats['inactive']}</text>
  <text class="label" x="589" y="68" text-anchor="middle">Inactive</text>

  <rect class="card" x="680" y="16" width="124" height="70"/>
  <text class="value" x="742" y="50" text-anchor="middle">{evidence_pct}%</text>
  <text class="label" x="742" y="68" text-anchor="middle">Evidence-backed</text>

  <!-- Row 2: Bars -->
  <rect class="card" x="16" y="102" width="388" height="62"/>
  <text class="title" x="32" y="124">Edge Types</text>
  <rect class="bar-bg" x="32" y="134" width="{bar_w}" height="8"/>
  <rect class="bar-rivalry" x="32" y="134" width="{rivalry_bar}" height="8"/>
  <text class="label" x="{32 + bar_w + 8}" y="142">Rivalry {stats['rivalry']}</text>
  <rect class="bar-bg" x="32" y="150" width="{bar_w}" height="8"/>
  <rect class="bar-alliance" x="32" y="150" width="{alliance_bar}" height="8"/>
  <text class="label" x="{32 + bar_w + 8}" y="158">Alliance {stats['alliance']}</text>

  <rect class="card" x="420" y="102" width="384" height="62"/>
  <text class="title" x="436" y="124">Evidence Coverage</text>
  <rect class="bar-bg" x="436" y="138" width="{bar_w}" height="12"/>
  <rect class="bar-evidence" x="436" y="138" width="{evidence_bar}" height="12"/>
  <text class="label" x="{436 + bar_w + 8}" y="149">{stats['evidence']:,} / {stats['edges']:,} edges have source quotes</text>
</svg>"""


def update_readme():
    content = README.read_text()
    # Replace STATS section with SVG embed
    stats_block = """<!-- STATS:START - Auto-generated by scripts/update-readme-stats.py -->
<img src=".github/assets/stats.svg" alt="Data Stats" width="100%">
<!-- STATS:END -->"""

    pattern = r"<!-- STATS:START.*?-->.*?<!-- STATS:END -->"
    if re.search(pattern, content, re.DOTALL):
        content = re.sub(pattern, stats_block, content, flags=re.DOTALL)
    README.write_text(content)


if __name__ == "__main__":
    stats = compute_stats()
    SVG_PATH.parent.mkdir(parents=True, exist_ok=True)
    SVG_PATH.write_text(generate_svg(stats))
    update_readme()
    print(f"Generated {SVG_PATH} and updated README.md")
