"""Generate stats section for README.md.

Run manually or via pre-commit hook.
Usage: python scripts/update-readme-stats.py
"""

import json
import re
from pathlib import Path
from collections import Counter

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"


def compute_stats():
    edges = json.loads((ROOT / "data/edges.json").read_text())
    orgs = [json.loads(f.read_text()) for f in (ROOT / "data/orgs").glob("*.json")]

    total_orgs = len(orgs)
    total_edges = len(edges)
    with_evidence = sum(1 for e in edges if e.get("evidence"))
    active = sum(1 for o in orgs if o.get("status") == "active")
    inactive = sum(1 for o in orgs if o.get("status") == "inactive")

    types = Counter(e["type"] for e in edges)
    metros = Counter(o.get("metro", "Unknown") for o in orgs)

    all_sources = []
    for o in orgs:
        for s in (o.get("sources") or []):
            url = s.get("url", "") if isinstance(s, dict) else ""
            domain = url.replace("https://", "").replace("http://", "").split("/")[0].replace("www.", "").replace("en.", "")
            if domain:
                all_sources.append(domain)
    source_domains = Counter(all_sources)

    # Build stats block
    stats = f"""<!-- STATS:START - Auto-generated by scripts/update-readme-stats.py -->
| Metric | Count |
|--------|-------|
| Organizations | {total_orgs:,} |
| Relationships | {total_edges:,} |
| Evidence-backed edges | {with_evidence:,} ({with_evidence*100//total_edges}%) |
| Active orgs | {active:,} |
| Inactive orgs | {inactive:,} |

| Edge Type | Count |
|-----------|-------|
| Rivalry | {types.get('rivalry', 0):,} |
| Alliance | {types.get('alliance', 0):,} |
| Member of | {types.get('member_of', 0):,} |
| Spin-off | {types.get('spin_off', 0):,} |
| Parent | {types.get('parent', 0):,} |

| Top Metros | Orgs |
|------------|------|
"""
    for metro, count in metros.most_common(5):
        stats += f"| {metro} | {count:,} |\n"

    stats += """<!-- STATS:END -->"""
    return stats


def update_readme(stats: str):
    content = README.read_text()
    pattern = r"<!-- STATS:START.*?-->.*?<!-- STATS:END -->"
    if re.search(pattern, content, re.DOTALL):
        content = re.sub(pattern, stats, content, flags=re.DOTALL)
    else:
        # Insert before ## Tech Stack
        content = content.replace("## Tech Stack", f"{stats}\n\n## Tech Stack")
    README.write_text(content)


if __name__ == "__main__":
    stats = compute_stats()
    update_readme(stats)
    print("README.md stats updated")
