"""Generate an SVG stats dashboard for README.md.

Run: python scripts/update-readme-stats.py
Outputs: .github/assets/stats.svg + updates README.md embed
"""

import json
import re
from pathlib import Path
from collections import Counter

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
SVG_PATH = ROOT / ".github" / "assets" / "stats.svg"

W = 780
PAD = 20


def compute_stats():
    edges = json.loads((ROOT / "data/edges.json").read_text())
    orgs = [json.loads(f.read_text()) for f in (ROOT / "data/orgs").glob("*.json")]

    sources = sum(len(o.get("sources") or []) for o in orgs)
    metros = len(set(o.get("metro", "") for o in orgs if o.get("metro")))
    with_colors = sum(1 for o in orgs if o.get("colors"))
    with_symbols = sum(1 for o in orgs if o.get("symbols"))

    return {
        "orgs": len(orgs),
        "edges": len(edges),
        "evidence": sum(1 for e in edges if e.get("evidence")),
        "active": sum(1 for o in orgs if o.get("status") == "active"),
        "inactive": sum(1 for o in orgs if o.get("status") == "inactive"),
        "rivalry": sum(1 for e in edges if e["type"] == "rivalry"),
        "alliance": sum(1 for e in edges if e["type"] == "alliance"),
        "member_of": sum(1 for e in edges if e["type"] == "member_of"),
        "spin_off": sum(1 for e in edges if e["type"] == "spin_off"),
        "sources": sources,
        "metros": metros,
        "with_colors": with_colors,
        "with_symbols": with_symbols,
    }


def generate_svg(s: dict) -> str:
    evidence_pct = s["evidence"] * 100 // s["edges"]
    # Bar widths (max 200px)
    bar_max = 200
    rivalry_w = bar_max * s["rivalry"] // s["edges"]
    alliance_w = bar_max * s["alliance"] // s["edges"]
    evidence_w = bar_max * evidence_pct // 100

    return f"""<svg width="{W}" height="170" viewBox="0 0 {W} 170" fill="none" xmlns="http://www.w3.org/2000/svg">
  <style>
    .label {{ font: 400 12px -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif; fill: #57606a; }}
    .value {{ font: 600 20px -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif; fill: #24292f; }}
    .small {{ font: 400 11px -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif; fill: #57606a; }}
    .bar-bg {{ fill: #eaeef2; rx: 3; }}
    .bar-red {{ fill: #cf222e; rx: 3; }}
    .bar-blue {{ fill: #0969da; rx: 3; }}
    .bar-green {{ fill: #1a7f37; rx: 3; }}
    @media (prefers-color-scheme: dark) {{
      .label {{ fill: #7d8590; }}
      .value {{ fill: #e6edf3; }}
      .small {{ fill: #7d8590; }}
      .bar-bg {{ fill: #21262d; }}
    }}
  </style>

  <!-- Border -->
  <rect x="0.5" y="0.5" width="{W-1}" height="169" rx="6" stroke="#d0d7de" stroke-opacity="0.4"/>

  <!-- Row 1: Stats -->
  <text class="value" x="{PAD}" y="42">{s['orgs']:,}</text>
  <text class="label" x="{PAD}" y="60">Organizations</text>

  <text class="value" x="180" y="42">{s['edges']:,}</text>
  <text class="label" x="180" y="60">Edges</text>

  <text class="value" x="320" y="42">{evidence_pct}%</text>
  <text class="label" x="320" y="60">Evidence-backed</text>

  <text class="value" x="500" y="42">{s['active']:,}</text>
  <text class="label" x="500" y="60">Active</text>

  <text class="value" x="620" y="42">{s['inactive']}</text>
  <text class="label" x="620" y="60">Inactive</text>

  <!-- Divider -->
  <line x1="{PAD}" y1="76" x2="{W-PAD}" y2="76" stroke="#d0d7de" stroke-opacity="0.3"/>

  <!-- Row 2: Bars -->
  <text class="small" x="{PAD}" y="100">Rivalry</text>
  <rect class="bar-bg" x="80" y="91" width="{bar_max}" height="10"/>
  <rect class="bar-red" x="80" y="91" width="{rivalry_w}" height="10"/>
  <text class="small" x="{80+bar_max+8}" y="100">{s['rivalry']:,}</text>

  <text class="small" x="{PAD}" y="120">Alliance</text>
  <rect class="bar-bg" x="80" y="111" width="{bar_max}" height="10"/>
  <rect class="bar-blue" x="80" y="111" width="{alliance_w}" height="10"/>
  <text class="small" x="{80+bar_max+8}" y="120">{s['alliance']:,}</text>

  <text class="small" x="{PAD}" y="140">Evidence</text>
  <rect class="bar-bg" x="80" y="131" width="{bar_max}" height="10"/>
  <rect class="bar-green" x="80" y="131" width="{evidence_w}" height="10"/>
  <text class="small" x="{80+bar_max+8}" y="140">{s['evidence']:,} / {s['edges']:,}</text>

  <!-- Right side mini stats -->
  <text class="small" x="420" y="100">{s['sources']:,} sources</text>
  <text class="small" x="420" y="120">{s['metros']} metros</text>
  <text class="small" x="420" y="140">{s['with_colors']} with colors</text>
  <text class="small" x="560" y="100">{s['member_of']} member_of</text>
  <text class="small" x="560" y="120">{s['spin_off']} spin-offs</text>
  <text class="small" x="560" y="140">{s['with_symbols']} with symbols</text>
</svg>"""


def update_readme():
    content = README.read_text()
    stats_block = """<!-- STATS:START - Auto-generated by scripts/update-readme-stats.py -->
<img src=".github/assets/stats.svg" alt="Data Stats" width="100%">
<!-- STATS:END -->"""

    pattern = r"<!-- STATS:START.*?-->.*?<!-- STATS:END -->"
    if re.search(pattern, content, re.DOTALL):
        content = re.sub(pattern, stats_block, content, flags=re.DOTALL)
    README.write_text(content)


if __name__ == "__main__":
    stats = compute_stats()
    SVG_PATH.parent.mkdir(parents=True, exist_ok=True)
    SVG_PATH.write_text(generate_svg(stats))
    update_readme()
    print(f"Generated {SVG_PATH}")
